# Generated by Django 5.0.7 on 2025-09-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
    ]
